#
# Module manifest for module 'build'
#
# Generated by: The Sharp Ninja
#
# Generated on: 10/9/2020
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'FreshBuild.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# ID used to uniquely identify this module
GUID = '9768ff68-595c-4da3-8ce4-bdaa552c20a5'

# Author of this module
Author = 'The Sharp Ninja'

# Company or vendor of this module
CompanyName = 'Gateway Programming School, Inc.'

# Copyright statement for this module
Copyright = '2020'

# Description of the functionality provided by this module
Description = 'Build up a Fresh System'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# List of all modules packaged with this module
ModuleList = @("FreshBuild")

# List of all files packaged with this module
FileList = @()
# FileList = @(
#     "Start-FreshBuild.ps1", 
#     "Search-FreshBuild.ps1", 
#     "Find-Sources.ps1",
#     "Get-ByCommand.ps1",
#     "Get-ByInstaller.ps1",
#     "Get-ByScoop.ps1",
#     "Get-Installer.ps1",
#     "Get-ByScript.ps1",
#     "Get-ByWinGet.ps1",
#     "Install-Software.ps1")

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{
        Prerelease     = 'beta'

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @("New-System", "Scoop", "WinGet", "Chocolatey", "Choco", "Cinst")

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/PS-Services/FreshBuild/LICENSE.md'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/PS-Services/FreshBuild'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'https://github.com/PS-Services/FreshBuild/ReleaseNotes.md'

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

